main.datasource.url = jdbc:hsqldb:file:.jmix/hsqldb/statemachine
main.datasource.username = sa
main.datasource.password =

jmix.ui.login-screen-id = LoginScreen
jmix.ui.main-screen-id = MainScreen
jmix.ui.menu-config = com/company/statemachine/menu.xml
jmix.ui.composite-menu = true

jmix.core.available-locales = en,ru
jmix.core.default-file-storage = fs

spring.messages.basename = com/company/statemachine/messages

logging.level.org.atmosphere = warn

# Liquibase
spring.liquibase.change-log = com/company/statemachine/liquibase/changelog.xml

server.servlet.session.timeout = 30m
